image: clojure:lein-2.8.1

pages:
  stage: deploy
  script:
  - lein do clean, cljsbuild once min
  - chmod -R og+rw resources/public
  - mv resources/public public
  artifacts:
    paths:
    - public
  only:
  - master
