image: clojure:lein-2.8.1

pages:
  stage: deploy
  script:
  - lein do clean, cljsbuild once min
  - chmod -R og+rw ./resources/public
  - rm -rf ./public
  - cp -r ./resources/public ./public
  artifacts:
    paths:
    - public
  only:
  - master
